# Starter pipeline
# Start with a minimal pipeline that you can customize to build and deploy your code.
# Add steps that build, run tests, deploy, and more:
# https://aka.ms/yaml

trigger:
  branches:
    include:
      - master
  paths:
    exclude:
    - .editorconfig
    - .gitattributes
    - .gitignore
    - LICENSE.TXT
    - README.md

name: $(Rev:r)

jobs:
- job: Windows

  pool:
    vmImage: 'windows-2019'

  variables:
    buildConfiguration: Release

  steps:
    - pwsh: |
        Write-Output 'BUILD_PR=$(SYSTEM.PULLREQUEST.PULLREQUESTNUMBER) BUILD_ID=$(BUILD.BUILDNUMBER)'
      displayName: "Echo the build variables"

    - pwsh: |
        [string]$latestTag=iex 'git describe --tags --abbrev=0'
        [string]$version="v$latestTag.$(BUILD.BUILDNUMBER)"
        Write-Output "##vso[build.updatebuildnumber]$version"
      displayName: "Get latest git tag"

    - task: UseDotNet@2
      displayName: "Add dotnet core 2.1"
      inputs:
        version: 2.1.x
        packageType: sdk
        includePreviewVersions: false

    - task: UseDotNet@2
      displayName: "Use dotnet core 3.1"
      inputs:
        version: 3.1.x
        packageType: sdk
        includePreviewVersions: true

    - task: DotNetCoreCLI@2
      displayName: "Restore packages"
      inputs:
        command: "restore"
        projects: "HoneycombSerilogSink.sln"

    - task: DotNetCoreCLI@2
      displayName: "Build"
      env:
        BUILD_PR: $(SYSTEM.PULLREQUEST.PULLREQUESTNUMBER)
        BUILD_ID: $(BUILD.BUILDNUMBER)
      inputs:
        command: "build"
        projects: "HoneycombSerilogSink.sln"
        arguments: '-c $(buildConfiguration)'

    - task: DotNetCoreCLI@2
      displayName: 'Test'
      inputs:
        command: 'test'
        projects: 'HoneycombSerilogSink.sln'
        arguments: '--no-restore --no-build -c $(buildConfiguration) --collect "Code coverage"'

    - task: DotNetCoreCLI@2
      displayName: 'Package'
      env:
        BUILD_PR: $(SYSTEM.PULLREQUEST.PULLREQUESTNUMBER)
        BUILD_ID: $(BUILD.BUILDNUMBER)
      inputs:
        command: 'pack'
        arguments: '.\src\Honeycomb.Serilog.Sink\Honeycomb.Serilog.Sink.csproj --output $(Build.ArtifactStagingDirectory) --configuration $(buildConfiguration) --no-build'

    - task: PublishBuildArtifacts@1
      displayName: 'Publish built artifacts'
      env:
        BUILD_PR: $(SYSTEM.PULLREQUEST.PULLREQUESTNUMBER)
        BUILD_ID: $(BUILD.BUILDNUMBER)
      inputs:
        PathtoPublish: '$(Build.ArtifactStagingDirectory)'
        ArtifactName: 'nuget'
        publishLocation: 'Container'
