# Starter pipeline
# Start with a minimal pipeline that you can customize to build and deploy your code.
# Add steps that build, run tests, deploy, and more:
# https://aka.ms/yaml
name: $(Rev:r)

trigger:
  branches:
    include:
      - master
  paths:
    exclude:
    - .editorconfig
    - .gitattributes
    - .gitignore
    - LICENSE.TXT
    - README.md

jobs:
- job: Windows

  pool:
    vmImage: 'windows-2019'

  variables:
    buildConfiguration: Release

  steps:
    - template: ci/templates/build-and-package.yml

    - pwsh: |
        Write-Host "##vso[build.updatebuildnumber]$(version)"