# Add steps that build, run tests, deploy, and more:
# https://aka.ms/yaml

name: $(Rev:r)

trigger:
  tags:
    include:
    - "*"

pr: none

pool:
  vmImage: 'windows-latest'

variables:
  buildConfiguration: Release

steps:
- pwsh: |
    [string]$latestTag=iex 'git describe --tags --abbrev=0'
    Write-Host "##vso[task.setvariable variable=releaseTag]$latestTag"
    Write-Host "##vso[build.updatebuildnumber]v$latestTag"
  displayName: "Set buld task name"

- template: ci/templates/build-and-package.yml

- task: NuGetCommand@2
  displayName: 'Push package to Nuget.org'
  inputs:
    command: push
    nuGetFeedType: external
    publishFeedCredentials: HoneycombSinkNugetFeed

- task: GitHubRelease@1
  inputs:
    gitHubConnection: GithubServiceConnection
    repositoryName: '$(Build.Repository.Name)'
    action: 'edit'
    target: '$(Build.SourceVersion)'
    releaseNotesSource: 'inline'
    changeLogCompareToRelease: 'lastFullRelease'
    changeLogType: 'commitBased'
    tag: $(releaseTag)
